image: node:8

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  script:
    - yarn
    - yarn bu
    - cd bin
    - yarn global add now
    - now --public --token=$NOW_API_KEY --team=lab
    - now alias live --token=$NOW_API_KEY --team=lab
    - now alias launch --token=$NOW_API_KEY --team=lab
    - now alias mail --token=$NOW_API_KEY --team=lab
    - now alias pay --token=$NOW_API_KEY --team=lab
    - now alias bin --token=$NOW_API_KEY --team=lab
    - now alias box --token=$NOW_API_KEY --team=lab
    - now alias hub --token=$NOW_API_KEY --team=lab
    - now alias job --token=$NOW_API_KEY --team=lab
    - now alias map --token=$NOW_API_KEY --team=lab
    - now alias labs --token=$NOW_API_KEY --team=lab
    - now alias ship --token=$NOW_API_KEY --team=lab
    - now alias photo --token=$NOW_API_KEY --team=lab
    - now alias search --token=$NOW_API_KEY --team=lab
    - now alias tezuka --token=$NOW_API_KEY --team=lab
    - now alias jiro --token=$NOW_API_KEY --team=lab
    - now alias ono --token=$NOW_API_KEY --team=lab
    - now rm dayflow --yes --safe --token=$NOW_API_KEY --team=lab || true
    - echo "Code deployed to now server"
    - git init
    - git config --global user.email "gitlab-ci@yah.vn"
    - git config --global user.name "GitLab CI"
    - git add .
    - git commit -am 'new deployment'
    # - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/dayflow.git
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/tezuka.git
    - git push heroku master --force
    - echo "Code deployed to heroku server"
  environment:
    name: deploy
    url: https://live.now.sh
  only:
    - master
