image: node:latest

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  script:
    - yarn
    - yarn build
    - yarn global add now
    - name=$(basename $(pwd))-$(git describe --tags --long)
    - deploy=$(now --name $name -e GIT_TAG=$name --public --token=$NOW_API_KEY --team=lab)
    - now alias $deploy live --token=$NOW_API_KEY --team=lab
    - now alias $deploy launch --token=$NOW_API_KEY --team=lab
    - now alias $deploy mail --token=$NOW_API_KEY --team=lab
    - now alias $deploy pay --token=$NOW_API_KEY --team=lab
    - now alias $deploy bin --token=$NOW_API_KEY --team=lab
    - now alias $deploy box --token=$NOW_API_KEY --team=lab
    - now alias $deploy hub --token=$NOW_API_KEY --team=lab
    - now alias $deploy job --token=$NOW_API_KEY --team=lab
    - now alias $deploy map --token=$NOW_API_KEY --team=lab
    - now alias $deploy labs --token=$NOW_API_KEY --team=lab
    - now alias $deploy ship --token=$NOW_API_KEY --team=lab
    - now alias $deploy photo --token=$NOW_API_KEY --team=lab
    - now alias $deploy search --token=$NOW_API_KEY --team=lab
    - now rm $name --yes --safe --token=$NOW_API_KEY --team=lab || true
    - echo "Code deployed to now server"
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/dayflow.git
    - git push heroku master
    - echo "Code deployed to heroku server"
  environment:
    name: deploy
    url: https://live.now.sh
  only:
    - master
