language: node_js
node_js:
  - stable
script:
  - yarn
  - yarn build
  - yarn global add now
  - now --public --token=$NOW_API_KEY --team=com
  - now alias travis --token=$NOW_API_KEY --team=com
  - now alias tezuka --token=$NOW_API_KEY --team=com
  - now alias jiro --token=$NOW_API_KEY --team=com
  - now alias ono --token=$NOW_API_KEY --team=com
  - now rm dayflow --yes --safe --token=$NOW_API_KEY --team=com || true
  - echo "Code deployed to now server"
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/tezuka.git
  - git push heroku master
  - echo "Code deployed to heroku server"
  - heroku config:set TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -a tezuka
