language: node_js
node_js:
  - stable
script:
  - yarn
  - yarn build
  - yarn global add now
  - name=dayflow-$(git describe --tags --long)
  - deploy=$(now --name $name -e GIT_TAG=$name --public --token=$NOW_API_KEY --team=com)
  - now alias $deploy travis --token=$NOW_API_KEY --team=com
  - now alias $deploy tezuka --token=$NOW_API_KEY --team=com
  - now alias $deploy jiro --token=$NOW_API_KEY --team=com
  - now alias $deploy ono --token=$NOW_API_KEY --team=com
  - now rm $name --yes --safe --token=$NOW_API_KEY --team=com || true
  - echo "Code deployed to now server"
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/tezuka.git
  - git push heroku master
  - echo "Code deployed to heroku server"
  - heroku config:set TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -a tezuka
