language: node_js
node_js:
  - 8
script:
  - yarn test
  - heroku config:set TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -a dayflow
after_success:
  - yarn build
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: uWWPG9E0pTHgXXRiQK5CAQbniel0G2T4mEHzITKn22hugDLI2GiDYPdhn+M8QsxYSoe1PMV4F841HduNrKPL99i9dou3DZUaS+UaE9Wth38QA9IXnGXzi/C51V0F/qTSbwuKyLA1MvQW5susnXnGcm8usyh6bIWmbBHHeRs+2hxd+nbCzIYU44a6Om/QDy0UNKEzh9E7mfZ+9KtUm9wpM6dr7tZbW2vOc/JX6Ft4VEUrlyHH/KXQm/qi65E1q+lGHq6A7KS8VaK4O/M5dL/S/BJeJMeeCkp6InT8YmsvL0YjkskO6Xj5AA9aisxIjoM92Da9ESZa3rjLs8vs8tFwq//VA4nk9XbJeUJnLeNtaI8b5ycwMoPBxSP2guAfQLGGpzIFG8HNDW/wvmW+C0kSjYSAfUX/1InSatIr2gUCTuVe3L0i7SD6NmNjWERDR6Q1cfDTxBxdZ3FmBrLsZHoeNbLeC7rHEAuvasYSyfDbpweI80OWy1aqPsj5jP42Xrtb92xXFOjkSxYemNkmWletGYPqhtYn32d6HNRAOXtP68iN8VMqDYE3M7iYKp5jxzihYpe5+IxvBbBl9dK8K8nd/X1YZYfSiwNAOSYYPh/DRp9NYOv6HCwIO9nGeMLaoT/nSyfqpP6ma7rFPgmoBCxDwSRrhGYWeu2ZaZZoboC87Qw=
  app:
    master: dayflow
  on:
    repo: hoang17/cube
env:
  global:
    - MONGODB_URI=mongodb://heroku_tr4w0c1r:bba2v931cuioerqbc91ush2k1v@ds153501.mlab.com:53501/heroku_tr4w0c1r
    - MONGOLAB_URI=mongodb://heroku_tr4w0c1r:bba2v931cuioerqbc91ush2k1v@ds153501.mlab.com:53501/heroku_tr4w0c1r
    - SESSION_SECRET=vhXn4fv3pzNDMXPvyina
    - MAILGUN_USER=postmaster@sandbox697fcddc09814c6b83718b9fd5d4e5dc.mailgun.org
    - MAILGUN_PASSWORD=29eldds1uri6
    - SENDGRID_USER=hslogin
    - SENDGRID_PASSWORD=hspassword00
    - SENDGRID_API_KEY=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
    - NYT_KEY=9548be6f3a64163d23e1539f067fcabd:5:68537648
    - LASTFM_KEY=c8c0ea1c4a6b199b3429722512fbd17f
    - LASTFM_SECRET=is cb7857b8fba83f819ea46ca13681fe71
    - FACEBOOK_ID=162469620476517
    - FACEBOOK_SECRET=741e4c093bc7aaa7387ee06d6d273d57
    - INSTAGRAM_ID=9f13482b65434e4ab9125f203e1ea6cd
    - INSTAGRAM_SECRET=f478273bd7f44f42bcde5c5ce88f1cfb
    - GITHUB_ID=cb448b1d4f0c743a1e36
    - GITHUB_SECRET=815aa4606f476444691c5f1c16b9c70da6714dc6
    - TWITTER_KEY=6NNBDyJ2TavL407A3lWxPFKBI
    - TWITTER_SECRET=ZHaYyK3DQCqv49Z9ofsYdqiUgeoICyh6uoBgFfu7OeYC7wTQKa
    - GOOGLE_ID=828110519058.apps.googleusercontent.com
    - GOOGLE_SECRET=JdZsIaWhUFIchmC1a_IZzOHb
    - LINKEDIN_ID=77chexmowru601
    - LINKEDIN_SECRET=szdC8lN2s2SuMSy8
    - LINKEDIN_CALLBACK_URL=http://localhost:3000/auth/linkedin/callback
    - STEAM_KEY=D1240DEF4D41D416FD291D0075B6ED3F
    - TWILIO_SID=AC6f0edc4c47becc6d0a952536fc9a6025
    - TWILIO_TOKEN=a67170ff7afa2df3f4c7d97cd240d0f3
    - CLOCKWORK_KEY=9ffb267f88df55762f74ba2f517a66dc8bedac5a
    - STRIPE_SKEY=sk_test_BQokikJOvBiI2HlWgH4olfQ2
    - STRIPE_PKEY=pk_test_6pRNASCoBOKtIshFeQd4XMUh
    - TUMBLR_KEY=FaXbGf5gkhswzDqSMYI42QCPYoHsu5MIDciAhTyYjehotQpJvM
    - TUMBLR_SECRET=QpCTs5IMMCsCImwdvFiqyGtIZwowF5o3UXonjPoNp4HVtJAL4o
    - FOURSQUARE_ID=2STROLSFBMZLAHG3IBA141EM2HGRF0IRIBB4KXMOGA2EH3JG
    - FOURSQUARE_SECRET=UAABFAWTIHIUFBL0PDC3TDMSXJF2GTGWLD3BES1QHXKAIYQB
    - FOURSQUARE_REDIRECT_URL=http://localhost:3000/auth/foursquare/callback
    - PAYPAL_ID=AdGE8hDyixVoHmbhASqAThfbBcrbcgiJPBwlAM7u7Kfq3YU-iPGc6BXaTppt
    - PAYPAL_SECRET=EPN0WxB5PaRaumTB1ZpCuuTqLqIlF6_EWUcAbZV99Eu86YeNBVm9KVsw_Ez5
    - PAYPAL_RETURN_URL=http://localhost:3000/api/paypal/success
    - PAYPAL_CANCEL_URL=http://localhost:3000/api/paypal/cancel
    - LOB_KEY=test_814e892b199d65ef6dbb3e4ad24689559ca
    - PINTEREST_ID=4819282851912494691
    - PINTEREST_SECRET=b32f578ad83d94c058c6682329220feda7e5817e043a1cc4a5a1e28f51c70301
    - PINTEREST_REDIRECT_URL=https://localhost:3000/auth/pinterest/callback
