# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:latest

pipelines:
  default:
  - step:
      caches:
      - node
      script:
      - npm i
      - npm run build
      - npm i -g --unsafe-perm now
      - now --name "$(basename $(pwd))-$(git describe --tags --long)" -e GIT_TAG="$(git describe --tags --long)" --public --token=$NOW_API_KEY --team=flow
      - now alias bit --token=$NOW_API_KEY --team=flow
      - now alias hoang --token=$NOW_API_KEY --team=flow
      - now alias sup --token=$NOW_API_KEY --team=flow
      - now alias sub --token=$NOW_API_KEY --team=flow
      - now alias shops --token=$NOW_API_KEY --team=flow
      - now alias stores --token=$NOW_API_KEY --team=flow
      - now alias top --token=$NOW_API_KEY --team=flow
      - now alias hot --token=$NOW_API_KEY --team=flow
      - now alias new --token=$NOW_API_KEY --team=flow
      - now rm dayflow --yes --safe --token=$NOW_API_KEY --team=flow || true
      - echo "Code deployed to now server"
      - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/acube.git
      - git push heroku master
      - echo "Code deployed to heroku server"
